# Generated by Django 4.0.4 on 2022-05-31 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('main_branch', models.CharField(max_length=500)),
                ('head_branch', models.CharField(max_length=500)),
                ('state', models.CharField(choices=[('open', 'open'), ('merged', 'merged'), ('merging', 'merging')], max_length=30)),
                ('git_id', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
